import type { Metadata } from "next";
import { GlobalLoadingProvider } from "@/components/providers/global-loading-provider";
import { AppProviders } from "@/components/providers/AppProviders";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <GlobalLoadingProvider>
          <AppProviders>
            {children}
            <Toaster position="top-right" richColors />
          </AppProviders>
        </GlobalLoadingProvider>
      </body>
    </html>
  );
}
